# Generated by Django 4.2.17 on 2025-05-28 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='ИНН должен состоять из 10 или 12 цифр', regex='^\\d{10}(\\d{2})?$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_inn',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен состоять из 10 или 12 цифр', regex='^\\d{10}(\\d{2})?$')]),
        ),
    ]
